apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-news-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-news-api
  template:
    metadata:
      labels:
        app: fake-news-api
    spec:
      containers:
        - name: fake-news-api
          image: fake-news-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
